#puro suco do template da internet
#mas td mundo faz isso ne ou to errado
#o cara do video disse q yml é melhor q .properties
#ent suave :)
#empregoLaVidVLibras?
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/readmaxxing
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update #cria as tabelas ao subir e deleta ao terminar
    show-sql: true #mostra os comandinho SQL no terminal tipo select * from coisinha
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect